# Generated by Django 6.0.4 on 2026-04-25 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AlterModelOptions(
            name='teamskill',
            options={'verbose_name': 'Team Skill', 'verbose_name_plural': 'Team Skills'},
        ),
        migrations.AlterField(
            model_name='department',
            name='departmentID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Department ID'),
        ),
        migrations.AlterField(
            model_name='department',
            name='departmentName',
            field=models.CharField(max_length=100, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='team.staff', verbose_name='Department Leader'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skillCategory',
            field=models.CharField(max_length=100, verbose_name='Skill Category'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skillID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Skill ID'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skillName',
            field=models.CharField(max_length=100, verbose_name='Skill Name'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='team.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='emailAddress',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='firstName',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='lastName',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staffID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Staff ID'),
        ),
        migrations.AlterField(
            model_name='team',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='team.department', verbose_name='Team Department'),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Team ID'),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamLeader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_teams', to='team.staff', verbose_name='Team Leader'),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamName',
            field=models.CharField(max_length=100, verbose_name='Team Name'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='dateJoined',
            field=models.DateField(blank=True, null=True, verbose_name='Date Joined'),
        ),
    ]
