# Generated by Django 6.0.4 on 2026-04-25 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_staff_options_alter_teammember_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='team.staff', verbose_name='Department Head'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='emailAddress',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
    ]
