# Generated by Django 6.0.4 on 2026-04-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_department_leader_alter_staff_emailaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='leader',
        ),
        migrations.AddField(
            model_name='department',
            name='leaders',
            field=models.ManyToManyField(blank=True, related_name='departments_led', to='team.staff', verbose_name='Department Head'),
        ),
    ]
