# Generated by Django 6.0.4 on 2026-04-26 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_remove_department_leader_department_leaders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='leaders',
        ),
        migrations.AddField(
            model_name='department',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='team.staff', verbose_name='Department Head'),
        ),
    ]
