# Generated by Django 6.0.4 on 2026-04-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_remove_department_leaders_department_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Development Focus Area')),
            ],
            options={
                'verbose_name': 'Development Focus Area',
                'verbose_name_plural': 'Development Focus Areas',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='developmentFocus',
            field=models.ManyToManyField(blank=True, to='team.developmentfocus', verbose_name='Development Focus Areas'),
        ),
    ]
