# Generated by Django 6.0.3 on 2026-04-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_team_slug_alter_teammember_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='developmentFocusAreas',
            field=models.TextField(blank=True, null=True, verbose_name='Focus Areas Text'),
        ),
        migrations.AddField(
            model_name='team',
            name='keySkills',
            field=models.TextField(blank=True, null=True, verbose_name='Key Skills & Technologies'),
        ),
        migrations.AlterField(
            model_name='team',
            name='developmentFocus',
            field=models.ManyToManyField(blank=True, to='team.developmentfocus', verbose_name='Development Focus Areas (Linked)'),
        ),
    ]
