# Generated by Django 6.0.3 on 2026-04-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_team_developmentfocusareas_team_keyskills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
    ]
