# Generated by Django 6.0.4 on 2026-04-25 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
        ('team', '0002_alter_staff_options_alter_teammember_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependencytype',
            options={'verbose_name': 'Dependency Type', 'verbose_name_plural': 'Dependency Types'},
        ),
        migrations.AlterModelOptions(
            name='teamdependency',
            options={'verbose_name': 'Team Dependency', 'verbose_name_plural': 'Team Dependencies'},
        ),
        migrations.AlterField(
            model_name='dependencytype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Dependency Type'),
        ),
        migrations.AlterField(
            model_name='teamdependency',
            name='depends_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_teams', to='team.team', verbose_name='Team it depends on'),
        ),
    ]
