# Generated by Django 6.0.4 on 2026-04-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_alter_dependencytype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdependency',
            name='direction',
            field=models.CharField(choices=[('UPSTREAM', 'Upstream'), ('DOWNSTREAM', 'Downstream')], default='UPSTREAM', max_length=20),
            preserve_default=False,
        ),
    ]
