# Generated by Django 6.0.4 on 2026-04-22 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=255)),
                ('team_role', models.CharField(max_length=255)),
                ('department_name', models.CharField(max_length=255)),
                ('department_head', models.CharField(max_length=255)),
                ('member_skills', models.TextField()),
                ('platform_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
