# Generated by Django 6.0.4 on 2026-04-22 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0002_platformprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_password_hash', models.CharField(max_length=255)),
                ('new_password_hash', models.CharField(max_length=255)),
                ('change_source', models.CharField(choices=[('reset', 'Reset')], default='reset', max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('platform_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
