# Generated by Django 6.0.4 on 2026-04-23 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0004_platformaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformDashboardActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_text', models.CharField(max_length=255)),
                ('activity_icon', models.CharField(choices=[('github', 'GitHub'), ('team', 'Team'), ('calendar', 'Calendar'), ('report', 'Report'), ('message', 'Message')], default='github', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformDashboardQuickToolSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_index', models.PositiveSmallIntegerField(choices=[(0, 'Slot 1'), (1, 'Slot 2'), (2, 'Slot 3')])),
                ('tool_id', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_quick_tool_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slot_index'],
                'constraints': [models.UniqueConstraint(fields=('platform_user', 'slot_index'), name='unique_dashboard_quick_tool_slot')],
            },
        ),
    ]
