# Generated by Django 6.0.4 on 2026-04-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0005_platformdashboardactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformprofile',
            name='profile_image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformprofile',
            name='profile_image_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
