# Generated by Django 6.0.4 on 2026-04-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0007_platforminboxmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='platforminboxmessage',
            name='draft_type',
            field=models.CharField(blank=True, choices=[('compose', 'Compose'), ('reply', 'Reply')], max_length=20),
        ),
        migrations.AddField(
            model_name='platforminboxmessage',
            name='message_mode',
            field=models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('drafts', 'Drafts')], default='inbox', max_length=20),
        ),
        migrations.AddField(
            model_name='platforminboxmessage',
            name='previous_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='platforminboxmessage',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='platforminboxmessage',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
