# Generated by Django 6.0.4 on 2026-04-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0008_platforminboxmessage_draft_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platforminboxmessage',
            name='is_hidden_from_user',
            field=models.BooleanField(default=False),
        ),
    ]
