# Generated by Django 6.0.4 on 2026-04-24 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0009_platforminboxmessage_is_hidden_from_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('team_lead', models.CharField(max_length=255)),
                ('github_link', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('review', 'On review'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('department_name', models.CharField(blank=True, max_length=255)),
                ('department_head', models.CharField(blank=True, max_length=255)),
                ('key_contact_1', models.CharField(blank=True, max_length=255)),
                ('key_contact_2', models.CharField(blank=True, max_length=255)),
                ('jira_project_name', models.CharField(blank=True, max_length=255)),
                ('jira_board_link', models.URLField(blank=True, max_length=500)),
                ('git_project_name', models.CharField(blank=True, max_length=255)),
                ('software_owned', models.CharField(blank=True, max_length=255)),
                ('versioning_approaches', models.CharField(blank=True, max_length=255)),
                ('wiki_link', models.URLField(blank=True, max_length=500)),
                ('wiki_search_terms', models.CharField(blank=True, max_length=255)),
                ('slack_channels', models.CharField(blank=True, max_length=500)),
                ('slack_link', models.URLField(blank=True, max_length=500)),
                ('daily_standup_time', models.TimeField(blank=True, null=True)),
                ('daily_standup_link', models.URLField(blank=True, max_length=500)),
                ('about_team', models.TextField(blank=True)),
                ('key_skills', models.TextField(blank=True)),
                ('focus_areas', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformTeamDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_name', models.CharField(max_length=255)),
                ('is_upstream', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('review', 'On review'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('updated_label', models.CharField(default='Recently', max_length=100)),
                ('platform_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_dependencies', to='login_page.platformteam')),
            ],
            options={
                'ordering': ['dependency_name'],
            },
        ),
    ]
