# Generated by Codex on 2026-04-25

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def get_unique_team_slug(PlatformTeam, teamName):
    baseSlug = slugify(teamName) or 'platform-team'
    nextSlug = baseSlug
    nextIndex = 2

    while PlatformTeam.objects.filter(slug=nextSlug).exists():
        nextSlug = f'{baseSlug}-{nextIndex}'
        nextIndex += 1

    return nextSlug


def seed_profile_team_assignments(apps, schema_editor):
    PlatformProfile = apps.get_model('login_page', 'PlatformProfile')
    PlatformTeam = apps.get_model('login_page', 'PlatformTeam')

    platformProfiles = PlatformProfile.objects.exclude(team_name='')
    for platformProfile in platformProfiles.iterator():
        teamName = (platformProfile.team_name or '').strip()
        if not teamName:
            continue

        platformTeam = PlatformTeam.objects.filter(name__iexact=teamName).first()
        if platformTeam is None:
            teamSlug = slugify(teamName) or 'platform-team'
            teamLead = platformProfile.full_name or 'Unassigned Team Lead'
            departmentName = platformProfile.department_name or ''
            platformTeam = PlatformTeam.objects.create(
                name=teamName,
                slug=get_unique_team_slug(PlatformTeam, teamName),
                team_lead=teamLead,
                github_link=f'https://github.com/sky/{teamSlug}',
                status='active',
                department_name=departmentName,
                department_head=platformProfile.department_head or '',
                key_contact_1=teamLead,
                key_contact_2=platformProfile.department_head or '',
                jira_project_name=teamName,
                jira_board_link=f'https://jira.example.com/{teamSlug}',
                git_project_name=teamName,
                wiki_link=f'https://wiki.example.com/{teamSlug}',
                slack_link='https://slack.com',
                about_team=(
                    f'{teamName} works inside {departmentName} '
                    f'with {teamLead} as the first allocated contact.'
                    if departmentName
                    else f'{teamName} has been seeded from user profile data.'
                ),
                key_skills=platformProfile.member_skills or '',
                focus_areas='Delivery Support | Team Coordination | System Integration',
            )

        PlatformProfile.objects.filter(pk=platformProfile.pk).update(
            platform_team=platformTeam,
            team_name=platformTeam.name,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0010_platformteam_platformteamdependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformprofile',
            name='platform_team',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='members',
                to='login_page.platformteam',
            ),
        ),
        migrations.AlterField(
            model_name='platformprofile',
            name='team_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(seed_profile_team_assignments, migrations.RunPython.noop),
    ]
