# Generated by Codex on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0011_platformprofile_platform_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformteam',
            name='team_image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformteam',
            name='team_image_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
