# Generated by Codex on 2026-04-26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login_page', '0012_platformteam_team_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('platform', models.CharField(max_length=100)),
                ('invite_members', models.CharField(max_length=500)),
                ('color', models.CharField(default='rgba(37, 99, 235, 1)', max_length=50)),
                ('color_secondary', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'platform_user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='schedule_events',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['event_date', 'start_time', 'id'],
            },
        ),
    ]
