# Generated by Django 6.0.4 on 2026-04-26 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0013_platformscheduleevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('report', 'Report'), ('chart', 'Chart')], default='report', max_length=10)),
                ('report_type', models.CharField(max_length=100)),
                ('doc_type', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel')], default='pdf', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('file_blob', models.BinaryField(blank=True, null=True)),
                ('file_content_type', models.CharField(blank=True, max_length=100)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
